server:
   port: 8080
   
spring: 
   jpa:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.SQLServer2012Dialect
      show-sql: true
   datasource:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://${SQLSERVER_URL}:${SQLSERVER_PORT};databaseName=${SQLSERVER_DATABASE}
      username: ${SQLSERVER_USER}
      password: ${SQLSERVER_PASSWORD}

auth:
  secret: 02b47ed8-3ffc-4f12-9762-7da56c50e258
  tokenPrefix: Bearer
  header: Authorization