
spring:
  server:
    port: 8080
  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:security
    driverClassName: org.h2.Driver
    username: root
    password: toor
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  config:
    activate:
      on-profile: test

auth:
  secret: 02b47ed8-3ffc-4f12-9762-7da56c50e258
  tokenPrefix: Bearer
  header: Authorization
