name: Build and Push Docker

on:
  [push]

jobs:
  build:
    environment: MySQL
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Run Commands with a Secret
      env:
        MYSQL_URL: ${{ secrets.MYSQL_URL }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      run: |
          echo MYSQL_URL=\"$MYSQL_URL\" > ./src/main/resources/application.yml
          echo MYSQL_DATABASE=\"$MYSQL_DATABASE\" > ./src/main/resources/application.yml
          echo MYSQL_USER=\"$MYSQL_USER\" > ./src/main/resources/application.yml
          echo MYSQL_PASSWORD=\"$MYSQL_PASSWORD\" > ./src/main/resources/application.yml
    - name: Build with Maven
      run: mvn clean package
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USR }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_TAG }}
